# Generated by Django 4.1.2 on 2022-10-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0002_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
