# Generated by Django 4.1.2 on 2022-10-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0004_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='musician',
        ),
    ]
