# Generated by Django 4.1.2 on 2022-10-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_application', '0005_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
